data:
  data_dir: 'data/meta'

train:
  epochs: 10000
  episodes: 5
  episode:
    task_cardinality: 10 # number of classes per task
    shots: 5 # the number of labelled samples per class ("support vectors")
    queries: 5 # the number of unlabelled samples per class ("query vectors"); they need to be classified in the right class
  optimization:
    learning_rate: 1.e-5
    decay_every: 20

model:
  encoder:
    model_name: 'bert-base-uncased'
    save_dir: null
  weight_decay: 0.
  save_dir: null

cuda: True
